vich_uploader:
    db_driver: orm
    mappings:
        category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        product:
            uri_prefix: /images/product
            upload_destination: '%kernel.project_dir%/public/images/product'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true